# Workflow para construir y desplegar una aplicación contenedor en Azure Web App
name: Build and deploy container app to Azure Web App - yankiservice

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configuration Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: https://cotainersbootcamp.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_743b56549022452eb31d6d879bde28fe }}
          password: ${{ secrets.AzureAppService_ContainerPassword_c78059bc58ad42c8974be13304e02654 }}

      # 4. Build and push Docker image
      - name: Build and push container image to ACR
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: cotainersbootcamp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_743b56549022452eb31d6d879bde28fe }}/yankiservice:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # 1. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'yankiservice'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_91e0fedd6b25418db5093bea731f550c }}
          images: 'cotainersbootcamp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_743b56549022452eb31d6d879bde28fe }}/yankiservice:${{ github.sha }}'
