# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - yankiservice

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cotainersbootcamp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_eccc3ce821814c47bc4c32e12c5ad617 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_36ca3366fa8940a693d4b77c2e9e2e2e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cotainersbootcamp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_eccc3ce821814c47bc4c32e12c5ad617 }}/yankiservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'yankiservice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8b039c946c6f47bc867bae41475eb848 }}
        images: 'cotainersbootcamp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_eccc3ce821814c47bc4c32e12c5ad617 }}/yankiservice:${{ github.sha }}'
